######################################################################
# Automatically generated by qmake (3.1) Wed Apr 16 15:27:32 2025
######################################################################

TEMPLATE = app
TARGET = test_ws
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += src/my_first_pkg/include/my_first_pkg/plus_minus.hpp
SOURCES += src/my_first_pkg/src/my_noed.cpp \
           src/my_first_pkg/src/plus_minus.cpp \
           src/my_first_pkg/src/test_UI.cpp \
           build/my_first_pkg/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
           build/my_first_pkg/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           src/build/my_first_pkg/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
           src/build/my_first_pkg/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp
TRANSLATIONS += build/my_first_pkg/CMakeFiles/my_first_pkg_uninstall.dir/compiler_depend.ts \
                build/my_first_pkg/CMakeFiles/my_noed.dir/compiler_depend.ts \
                build/my_first_pkg/CMakeFiles/test_UI.dir/compiler_depend.ts \
                build/my_first_pkg/CMakeFiles/uninstall.dir/compiler_depend.ts \
                src/build/my_first_pkg/CMakeFiles/my_first_pkg_uninstall.dir/compiler_depend.ts \
                src/build/my_first_pkg/CMakeFiles/my_noed.dir/compiler_depend.ts \
                src/build/my_first_pkg/CMakeFiles/uninstall.dir/compiler_depend.ts
