amcl:
  ros__parameters:
    use_sim_time: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    global_frame_id: "map"
    scan_topic: "base_scan"
    resample_interval: 1      # → ruhig auch auf 2–3 setzen, um Glättung zu verbessern
    update_min_d: 0.05        # → kleinere Bewegung reicht zum Update
    update_min_a: 0.05
    min_particles: 1000       # mehr Partikel für bessere Schätzung
    max_particles: 3000
    transform_tolerance: 0.1  # kleiner, wenn du Timingprobleme vermeiden willst
    laser_min_range: 0.0
    laser_max_range: 100.0
    set_initial_pose: true
    initial_pose:
      x: -4.0
      y: -4.0
      z: 0.0
      yaw: 0.785398
    publish_particle_cloud: true
