# This file shold be in stage_ros2/world/bitmaps/ to be detected
image: cave.png
resolution: 0.02            # ← oder was auch immer in der .world unter 'resolution' steht
origin: [-5.0, -5.0, 0.7854]     # ← [x, y, yaw] – oft [0.0, 0.0, 0.0], je nach Welt
negate: 0                   # ← 0 = Schwarz ist belegt (Stage-Standard)
occupied_thresh: 0.65
free_thresh: 0.196
